---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiger-backend-ingress
  namespace: tiger
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.tiger-corporation-vietnam.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tiger-backend
                port:
                  number: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: tiger-backend
  namespace: tiger
spec:
  selector:
    app: tiger-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-backend
  namespace: tiger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiger-backend
  template:
    metadata:
      labels:
        app: tiger-backend
    spec:
      volumes:
        - name: shared-secret
          emptyDir: {}
        - name: aws-config
          hostPath:
            path: /home/ubuntu/aws
            type: Directory

      initContainers:
        - name: init-env-sidecar
          image: tuandoquoc/export-ssm-to-env:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "--path=/tiger-backend/"
            - "--region=ap-southeast-1"
            - "--env-file=/var/secret/.env"
          volumeMounts:
            - name: shared-secret
              mountPath: /var/secret
            - name: aws-config
              mountPath: /root/.aws
              readOnly: true

      containers:
        - name: tiger-backend
          image: tuandoquoc/tiger-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: tiger-app-secret
            - configMapRef:
                name: tiger-app-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          command:
            - "/bin/sh"
            - "-c"
            - |
              export $(grep -v '^#' /var/secret/.env | xargs) && exec npm run start:prod
          volumeMounts:
            - name: shared-secret
              mountPath: /var/secret
