apiVersion: v1
kind: Secret
metadata:
  name: tiger-app-secret
  namespace: tiger
type: Opaque
stringData:
  # Database
  DATABASE_URL: "Vault"

  # JWT
  JWT_SECRET: "Vault"
  JWT_REFRESH_SECRET: "Vault"

  # S3 / MinIO
  S3_ACCESS_KEY_ID: "Vault"
  S3_SECRET_ACCESS_KEY: "Vault"

  # Cloudinary
  CLOUDINARY_URL: "cloudinary://api_key:api_secret@cloud_name"
  # OAuth Google
  OAUTH_GOOGLE_CLIENT_ID: "Vault"
  OAUTH_GOOGLE_CLIENT_SECRET: "Vault"

  # OAuth Facebook
  OAUTH_FB_CLIENT_ID: "Vault"
  OAUTH_FB_CLIENT_SECRET: "Vault"
